/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_LOGIN (void);
GtkWidget* create_ADMIN (void);
GtkWidget* create_AJOUT (void);
GtkWidget* create_SUPP (void);
GtkWidget* create_RECHERCHE (void);
GtkWidget* create_MODIF (void);
