/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_LOGIN (void)
{
  GtkWidget *LOGIN;
  GtkWidget *fixed1;
  GtkWidget *entry1_login;
  GtkWidget *entry2_login;
  GtkWidget *label2;
  GtkWidget *label1;
  GtkWidget *button_ok;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label3;

  LOGIN = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (LOGIN, 600, 200);
  gtk_window_set_title (GTK_WINDOW (LOGIN), _("LOGIN"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (LOGIN), fixed1);

  entry1_login = gtk_entry_new ();
  gtk_widget_show (entry1_login);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1_login, 224, 40);
  gtk_widget_set_size_request (entry1_login, 168, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_login), 8226);

  entry2_login = gtk_entry_new ();
  gtk_widget_show (entry2_login);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2_login, 224, 80);
  gtk_widget_set_size_request (entry2_login, 168, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2_login), 8226);

  label2 = gtk_label_new (_("password:"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 104, 88);
  gtk_widget_set_size_request (label2, 112, 24);

  label1 = gtk_label_new (_("username:"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 120, 48);
  gtk_widget_set_size_request (label1, 72, 24);

  button_ok = gtk_button_new ();
  gtk_widget_show (button_ok);
  gtk_fixed_put (GTK_FIXED (fixed1), button_ok, 224, 120);
  gtk_widget_set_size_request (button_ok, 72, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button_ok), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("login"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox1), label3, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_ok, "clicked",
                    G_CALLBACK (on_button_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (LOGIN, LOGIN, "LOGIN");
  GLADE_HOOKUP_OBJECT (LOGIN, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (LOGIN, entry1_login, "entry1_login");
  GLADE_HOOKUP_OBJECT (LOGIN, entry2_login, "entry2_login");
  GLADE_HOOKUP_OBJECT (LOGIN, label2, "label2");
  GLADE_HOOKUP_OBJECT (LOGIN, label1, "label1");
  GLADE_HOOKUP_OBJECT (LOGIN, button_ok, "button_ok");
  GLADE_HOOKUP_OBJECT (LOGIN, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (LOGIN, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (LOGIN, image1, "image1");
  GLADE_HOOKUP_OBJECT (LOGIN, label3, "label3");

  return LOGIN;
}

GtkWidget*
create_ADMIN (void)
{
  GtkWidget *ADMIN;
  GtkWidget *fixed2;
  GtkWidget *treeview1;
  GtkWidget *button_goajout;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *label7;
  GtkWidget *button_gorech;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *label10;
  GtkWidget *button_gomodif;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label8;
  GtkWidget *button_gosupp;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label9;
  GtkWidget *button_affich;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image15;
  GtkWidget *label26;

  ADMIN = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ADMIN), _("Espace admin"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (ADMIN), fixed2);
  gtk_widget_set_size_request (fixed2, 600, 400);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1, 56, 64);
  gtk_widget_set_size_request (treeview1, 832, 456);

  button_goajout = gtk_button_new ();
  gtk_widget_show (button_goajout);
  gtk_fixed_put (GTK_FIXED (fixed2), button_goajout, 168, 8);
  gtk_widget_set_size_request (button_goajout, 104, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_goajout), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox2), label7, FALSE, FALSE, 0);

  button_gorech = gtk_button_new ();
  gtk_widget_show (button_gorech);
  gtk_fixed_put (GTK_FIXED (fixed2), button_gorech, 280, 8);
  gtk_widget_set_size_request (button_gorech, 104, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_gorech), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox5), label10, FALSE, FALSE, 0);

  button_gomodif = gtk_button_new ();
  gtk_widget_show (button_gomodif);
  gtk_fixed_put (GTK_FIXED (fixed2), button_gomodif, 392, 8);
  gtk_widget_set_size_request (button_gomodif, 104, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_gomodif), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox3), label8, FALSE, FALSE, 0);

  button_gosupp = gtk_button_new ();
  gtk_widget_show (button_gosupp);
  gtk_fixed_put (GTK_FIXED (fixed2), button_gosupp, 504, 8);
  gtk_widget_set_size_request (button_gosupp, 104, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_gosupp), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox4), label9, FALSE, FALSE, 0);

  button_affich = gtk_button_new ();
  gtk_widget_show (button_affich);
  gtk_fixed_put (GTK_FIXED (fixed2), button_affich, 56, 8);
  gtk_widget_set_size_request (button_affich, 104, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_affich), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image15 = gtk_image_new_from_stock ("gtk-justify-left", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox10), image15, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox10), label26, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_goajout, "clicked",
                    G_CALLBACK (on_button_goajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_gorech, "clicked",
                    G_CALLBACK (on_button_gorech_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_gomodif, "clicked",
                    G_CALLBACK (on_button_gomodif_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_gosupp, "clicked",
                    G_CALLBACK (on_button_gosupp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_affich, "clicked",
                    G_CALLBACK (on_button_affich_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ADMIN, ADMIN, "ADMIN");
  GLADE_HOOKUP_OBJECT (ADMIN, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (ADMIN, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (ADMIN, button_goajout, "button_goajout");
  GLADE_HOOKUP_OBJECT (ADMIN, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (ADMIN, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (ADMIN, image3, "image3");
  GLADE_HOOKUP_OBJECT (ADMIN, label7, "label7");
  GLADE_HOOKUP_OBJECT (ADMIN, button_gorech, "button_gorech");
  GLADE_HOOKUP_OBJECT (ADMIN, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (ADMIN, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (ADMIN, image6, "image6");
  GLADE_HOOKUP_OBJECT (ADMIN, label10, "label10");
  GLADE_HOOKUP_OBJECT (ADMIN, button_gomodif, "button_gomodif");
  GLADE_HOOKUP_OBJECT (ADMIN, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (ADMIN, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (ADMIN, image4, "image4");
  GLADE_HOOKUP_OBJECT (ADMIN, label8, "label8");
  GLADE_HOOKUP_OBJECT (ADMIN, button_gosupp, "button_gosupp");
  GLADE_HOOKUP_OBJECT (ADMIN, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (ADMIN, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (ADMIN, image5, "image5");
  GLADE_HOOKUP_OBJECT (ADMIN, label9, "label9");
  GLADE_HOOKUP_OBJECT (ADMIN, button_affich, "button_affich");
  GLADE_HOOKUP_OBJECT (ADMIN, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (ADMIN, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (ADMIN, image15, "image15");
  GLADE_HOOKUP_OBJECT (ADMIN, label26, "label26");

  return ADMIN;
}

GtkWidget*
create_AJOUT (void)
{
  GtkWidget *AJOUT;
  GtkWidget *fixed3;
  GtkWidget *entry1_ajout;
  GtkWidget *entry2_ajout;
  GtkWidget *entry3_ajout;
  GtkWidget *entry4_ajout;
  GtkObject *spinbutton1_ajout_adj;
  GtkWidget *spinbutton1_ajout;
  GtkWidget *ajout_erreur;
  GtkWidget *Home_ajout;
  GtkWidget *image16;
  GtkWidget *label_back_add_to_home;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label14;
  GtkWidget *radiobutton2_ajout;
  GSList *radiobutton2_ajout_group = NULL;
  GtkWidget *label15;
  GtkWidget *radiobutton1_ajout;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label_choisir_role;
  GtkWidget *button_ajouter;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image8;
  GtkWidget *label18;
  GtkWidget *label13;
  GtkWidget *combobox1_ajout;

  AJOUT = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (AJOUT), _("Fenetre ajout"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (AJOUT), fixed3);

  entry1_ajout = gtk_entry_new ();
  gtk_widget_show (entry1_ajout);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1_ajout, 280, 64);
  gtk_widget_set_size_request (entry1_ajout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_ajout), 8226);

  entry2_ajout = gtk_entry_new ();
  gtk_widget_show (entry2_ajout);
  gtk_fixed_put (GTK_FIXED (fixed3), entry2_ajout, 280, 104);
  gtk_widget_set_size_request (entry2_ajout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2_ajout), 8226);

  entry3_ajout = gtk_entry_new ();
  gtk_widget_show (entry3_ajout);
  gtk_fixed_put (GTK_FIXED (fixed3), entry3_ajout, 280, 144);
  gtk_widget_set_size_request (entry3_ajout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3_ajout), 8226);

  entry4_ajout = gtk_entry_new ();
  gtk_widget_show (entry4_ajout);
  gtk_fixed_put (GTK_FIXED (fixed3), entry4_ajout, 280, 184);
  gtk_widget_set_size_request (entry4_ajout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4_ajout), 8226);

  spinbutton1_ajout_adj = gtk_adjustment_new (1, 1, 2, 1, 10, 10);
  spinbutton1_ajout = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_ajout_adj), 1, 0);
  gtk_widget_show (spinbutton1_ajout);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton1_ajout, 288, 312);
  gtk_widget_set_size_request (spinbutton1_ajout, 152, 24);

  ajout_erreur = gtk_label_new ("");
  gtk_widget_show (ajout_erreur);
  gtk_fixed_put (GTK_FIXED (fixed3), ajout_erreur, 24, 464);
  gtk_widget_set_size_request (ajout_erreur, 376, 24);

  Home_ajout = gtk_button_new ();
  gtk_widget_show (Home_ajout);
  gtk_fixed_put (GTK_FIXED (fixed3), Home_ajout, 16, 8);
  gtk_widget_set_size_request (Home_ajout, 32, 32);

  image16 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_container_add (GTK_CONTAINER (Home_ajout), image16);

  label_back_add_to_home = gtk_label_new (_("Retour au dashboard"));
  gtk_widget_show (label_back_add_to_home);
  gtk_fixed_put (GTK_FIXED (fixed3), label_back_add_to_home, 48, 16);
  gtk_widget_set_size_request (label_back_add_to_home, 152, 16);

  label11 = gtk_label_new (_("Nom"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed3), label11, 216, 72);
  gtk_widget_set_size_request (label11, 49, 17);

  label12 = gtk_label_new (_("Id"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed3), label12, 216, 112);
  gtk_widget_set_size_request (label12, 49, 17);

  label14 = gtk_label_new (_("Mot de passe "));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 168, 184);
  gtk_widget_set_size_request (label14, 104, 32);

  radiobutton2_ajout = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton2_ajout);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton2_ajout, 368, 272);
  gtk_widget_set_size_request (radiobutton2_ajout, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2_ajout), radiobutton2_ajout_group);
  radiobutton2_ajout_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2_ajout));

  label15 = gtk_label_new (_("Type"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 216, 232);
  gtk_widget_set_size_request (label15, 49, 17);

  radiobutton1_ajout = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton1_ajout);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton1_ajout, 280, 272);
  gtk_widget_set_size_request (radiobutton1_ajout, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1_ajout), radiobutton2_ajout_group);
  radiobutton2_ajout_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1_ajout));

  label16 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 216, 280);
  gtk_widget_set_size_request (label16, 49, 17);

  label17 = gtk_label_new (_("Role"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 216, 320);
  gtk_widget_set_size_request (label17, 49, 17);

  label_choisir_role = gtk_label_new (_("Role : 1 - Admin | 2 - Ouvrier | 3 - Technicien"));
  gtk_widget_show (label_choisir_role);
  gtk_fixed_put (GTK_FIXED (fixed3), label_choisir_role, 192, 368);
  gtk_widget_set_size_request (label_choisir_role, 304, 32);

  button_ajouter = gtk_button_new ();
  gtk_widget_show (button_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed3), button_ajouter, 304, 432);
  gtk_widget_set_size_request (button_ajouter, 88, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_ajouter), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image8 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox6), image8, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox6), label18, FALSE, FALSE, 0);

  label13 = gtk_label_new (_("Username"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 184, 144);
  gtk_widget_set_size_request (label13, 88, 32);

  combobox1_ajout = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1_ajout);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox1_ajout, 280, 224);
  gtk_widget_set_size_request (combobox1_ajout, 160, 24);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_ajout), _("Admin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_ajout), _("Ouvrier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_ajout), _("Technicien"));

  g_signal_connect ((gpointer) Home_ajout, "clicked",
                    G_CALLBACK (on_Home_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2_ajout, "toggled",
                    G_CALLBACK (on_radiobutton2_ajout_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_ajout, "toggled",
                    G_CALLBACK (on_radiobutton1_ajout_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_ajouter, "clicked",
                    G_CALLBACK (on_button_ajouter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (AJOUT, AJOUT, "AJOUT");
  GLADE_HOOKUP_OBJECT (AJOUT, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (AJOUT, entry1_ajout, "entry1_ajout");
  GLADE_HOOKUP_OBJECT (AJOUT, entry2_ajout, "entry2_ajout");
  GLADE_HOOKUP_OBJECT (AJOUT, entry3_ajout, "entry3_ajout");
  GLADE_HOOKUP_OBJECT (AJOUT, entry4_ajout, "entry4_ajout");
  GLADE_HOOKUP_OBJECT (AJOUT, spinbutton1_ajout, "spinbutton1_ajout");
  GLADE_HOOKUP_OBJECT (AJOUT, ajout_erreur, "ajout_erreur");
  GLADE_HOOKUP_OBJECT (AJOUT, Home_ajout, "Home_ajout");
  GLADE_HOOKUP_OBJECT (AJOUT, image16, "image16");
  GLADE_HOOKUP_OBJECT (AJOUT, label_back_add_to_home, "label_back_add_to_home");
  GLADE_HOOKUP_OBJECT (AJOUT, label11, "label11");
  GLADE_HOOKUP_OBJECT (AJOUT, label12, "label12");
  GLADE_HOOKUP_OBJECT (AJOUT, label14, "label14");
  GLADE_HOOKUP_OBJECT (AJOUT, radiobutton2_ajout, "radiobutton2_ajout");
  GLADE_HOOKUP_OBJECT (AJOUT, label15, "label15");
  GLADE_HOOKUP_OBJECT (AJOUT, radiobutton1_ajout, "radiobutton1_ajout");
  GLADE_HOOKUP_OBJECT (AJOUT, label16, "label16");
  GLADE_HOOKUP_OBJECT (AJOUT, label17, "label17");
  GLADE_HOOKUP_OBJECT (AJOUT, label_choisir_role, "label_choisir_role");
  GLADE_HOOKUP_OBJECT (AJOUT, button_ajouter, "button_ajouter");
  GLADE_HOOKUP_OBJECT (AJOUT, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (AJOUT, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (AJOUT, image8, "image8");
  GLADE_HOOKUP_OBJECT (AJOUT, label18, "label18");
  GLADE_HOOKUP_OBJECT (AJOUT, label13, "label13");
  GLADE_HOOKUP_OBJECT (AJOUT, combobox1_ajout, "combobox1_ajout");

  return AJOUT;
}

GtkWidget*
create_SUPP (void)
{
  GtkWidget *SUPP;
  GtkWidget *fixed4;
  GtkWidget *entry1_supp;
  GtkWidget *label19;
  GtkWidget *button_supp;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image10;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *button_homesupp;
  GtkWidget *image9;
  GtkWidget *label32;

  SUPP = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (SUPP), _("Fenetre supprimer"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (SUPP), fixed4);

  entry1_supp = gtk_entry_new ();
  gtk_widget_show (entry1_supp);
  gtk_fixed_put (GTK_FIXED (fixed4), entry1_supp, 120, 80);
  gtk_widget_set_size_request (entry1_supp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_supp), 8226);

  label19 = gtk_label_new (_("Saisir l'id"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 40, 88);
  gtk_widget_set_size_request (label19, 72, 16);

  button_supp = gtk_button_new ();
  gtk_widget_show (button_supp);
  gtk_fixed_put (GTK_FIXED (fixed4), button_supp, 136, 136);
  gtk_widget_set_size_request (button_supp, 104, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_supp), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image10 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox7), image10, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox7), label20, FALSE, FALSE, 0);

  label21 = gtk_label_new ("");
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed4), label21, 80, 192);
  gtk_widget_set_size_request (label21, 232, 32);

  button_homesupp = gtk_button_new ();
  gtk_widget_show (button_homesupp);
  gtk_fixed_put (GTK_FIXED (fixed4), button_homesupp, 8, 8);
  gtk_widget_set_size_request (button_homesupp, 32, 32);

  image9 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_container_add (GTK_CONTAINER (button_homesupp), image9);

  label32 = gtk_label_new (_("Retour au dashboard"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed4), label32, 40, 16);
  gtk_widget_set_size_request (label32, 160, 16);

  g_signal_connect ((gpointer) button_supp, "clicked",
                    G_CALLBACK (on_button_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_homesupp, "clicked",
                    G_CALLBACK (on_button_homesupp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (SUPP, SUPP, "SUPP");
  GLADE_HOOKUP_OBJECT (SUPP, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (SUPP, entry1_supp, "entry1_supp");
  GLADE_HOOKUP_OBJECT (SUPP, label19, "label19");
  GLADE_HOOKUP_OBJECT (SUPP, button_supp, "button_supp");
  GLADE_HOOKUP_OBJECT (SUPP, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (SUPP, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (SUPP, image10, "image10");
  GLADE_HOOKUP_OBJECT (SUPP, label20, "label20");
  GLADE_HOOKUP_OBJECT (SUPP, label21, "label21");
  GLADE_HOOKUP_OBJECT (SUPP, button_homesupp, "button_homesupp");
  GLADE_HOOKUP_OBJECT (SUPP, image9, "image9");
  GLADE_HOOKUP_OBJECT (SUPP, label32, "label32");

  return SUPP;
}

GtkWidget*
create_RECHERCHE (void)
{
  GtkWidget *RECHERCHE;
  GtkWidget *fixed5;
  GtkWidget *entry_rech;
  GtkWidget *pw;
  GtkWidget *username;
  GtkWidget *role;
  GtkWidget *sexe;
  GtkWidget *type;
  GtkWidget *nom;
  GtkWidget *aa1;
  GtkWidget *aa2;
  GtkWidget *aa3;
  GtkWidget *aa4;
  GtkWidget *aa5;
  GtkWidget *aa6;
  GtkWidget *notrecherche;
  GtkWidget *button_homerech;
  GtkWidget *image12;
  GtkWidget *label33;
  GtkWidget *label22;
  GtkWidget *button_aff;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image11;
  GtkWidget *label23;

  RECHERCHE = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (RECHERCHE), _("Fenetre recherche"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (RECHERCHE), fixed5);
  gtk_widget_set_size_request (fixed5, 400, 200);

  entry_rech = gtk_entry_new ();
  gtk_widget_show (entry_rech);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_rech, 144, 64);
  gtk_widget_set_size_request (entry_rech, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_rech), 8226);

  pw = gtk_label_new ("");
  gtk_widget_show (pw);
  gtk_fixed_put (GTK_FIXED (fixed5), pw, 144, 408);
  gtk_widget_set_size_request (pw, 144, 40);

  username = gtk_label_new ("");
  gtk_widget_show (username);
  gtk_fixed_put (GTK_FIXED (fixed5), username, 144, 376);
  gtk_widget_set_size_request (username, 144, 32);

  role = gtk_label_new ("");
  gtk_widget_show (role);
  gtk_fixed_put (GTK_FIXED (fixed5), role, 144, 336);
  gtk_widget_set_size_request (role, 144, 40);

  sexe = gtk_label_new ("");
  gtk_widget_show (sexe);
  gtk_fixed_put (GTK_FIXED (fixed5), sexe, 144, 304);
  gtk_widget_set_size_request (sexe, 144, 32);

  type = gtk_label_new ("");
  gtk_widget_show (type);
  gtk_fixed_put (GTK_FIXED (fixed5), type, 144, 264);
  gtk_widget_set_size_request (type, 144, 32);

  nom = gtk_label_new ("");
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed5), nom, 144, 232);
  gtk_widget_set_size_request (nom, 144, 32);

  aa1 = gtk_label_new ("");
  gtk_widget_show (aa1);
  gtk_fixed_put (GTK_FIXED (fixed5), aa1, 0, 224);
  gtk_widget_set_size_request (aa1, 96, 40);

  aa2 = gtk_label_new ("");
  gtk_widget_show (aa2);
  gtk_fixed_put (GTK_FIXED (fixed5), aa2, 0, 264);
  gtk_widget_set_size_request (aa2, 96, 40);

  aa3 = gtk_label_new ("");
  gtk_widget_show (aa3);
  gtk_fixed_put (GTK_FIXED (fixed5), aa3, 0, 296);
  gtk_widget_set_size_request (aa3, 96, 48);

  aa4 = gtk_label_new ("");
  gtk_widget_show (aa4);
  gtk_fixed_put (GTK_FIXED (fixed5), aa4, 0, 336);
  gtk_widget_set_size_request (aa4, 96, 48);

  aa5 = gtk_label_new ("");
  gtk_widget_show (aa5);
  gtk_fixed_put (GTK_FIXED (fixed5), aa5, 0, 376);
  gtk_widget_set_size_request (aa5, 112, 32);

  aa6 = gtk_label_new ("");
  gtk_widget_show (aa6);
  gtk_fixed_put (GTK_FIXED (fixed5), aa6, 0, 408);
  gtk_widget_set_size_request (aa6, 96, 32);

  notrecherche = gtk_label_new ("");
  gtk_widget_show (notrecherche);
  gtk_fixed_put (GTK_FIXED (fixed5), notrecherche, 8, 176);
  gtk_widget_set_size_request (notrecherche, 360, 32);

  button_homerech = gtk_button_new ();
  gtk_widget_show (button_homerech);
  gtk_fixed_put (GTK_FIXED (fixed5), button_homerech, 16, 8);
  gtk_widget_set_size_request (button_homerech, 32, 32);

  image12 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_container_add (GTK_CONTAINER (button_homerech), image12);

  label33 = gtk_label_new (_("Retour au dashboard"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed5), label33, 48, 16);
  gtk_widget_set_size_request (label33, 160, 16);

  label22 = gtk_label_new (_("Saisir l'id"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed5), label22, 64, 72);
  gtk_widget_set_size_request (label22, 88, 16);

  button_aff = gtk_button_new ();
  gtk_widget_show (button_aff);
  gtk_fixed_put (GTK_FIXED (fixed5), button_aff, 144, 104);
  gtk_widget_set_size_request (button_aff, 120, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_aff), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image11 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox8), image11, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox8), label23, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_homerech, "clicked",
                    G_CALLBACK (on_button_homerech_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_aff, "clicked",
                    G_CALLBACK (on_button_aff_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (RECHERCHE, RECHERCHE, "RECHERCHE");
  GLADE_HOOKUP_OBJECT (RECHERCHE, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (RECHERCHE, entry_rech, "entry_rech");
  GLADE_HOOKUP_OBJECT (RECHERCHE, pw, "pw");
  GLADE_HOOKUP_OBJECT (RECHERCHE, username, "username");
  GLADE_HOOKUP_OBJECT (RECHERCHE, role, "role");
  GLADE_HOOKUP_OBJECT (RECHERCHE, sexe, "sexe");
  GLADE_HOOKUP_OBJECT (RECHERCHE, type, "type");
  GLADE_HOOKUP_OBJECT (RECHERCHE, nom, "nom");
  GLADE_HOOKUP_OBJECT (RECHERCHE, aa1, "aa1");
  GLADE_HOOKUP_OBJECT (RECHERCHE, aa2, "aa2");
  GLADE_HOOKUP_OBJECT (RECHERCHE, aa3, "aa3");
  GLADE_HOOKUP_OBJECT (RECHERCHE, aa4, "aa4");
  GLADE_HOOKUP_OBJECT (RECHERCHE, aa5, "aa5");
  GLADE_HOOKUP_OBJECT (RECHERCHE, aa6, "aa6");
  GLADE_HOOKUP_OBJECT (RECHERCHE, notrecherche, "notrecherche");
  GLADE_HOOKUP_OBJECT (RECHERCHE, button_homerech, "button_homerech");
  GLADE_HOOKUP_OBJECT (RECHERCHE, image12, "image12");
  GLADE_HOOKUP_OBJECT (RECHERCHE, label33, "label33");
  GLADE_HOOKUP_OBJECT (RECHERCHE, label22, "label22");
  GLADE_HOOKUP_OBJECT (RECHERCHE, button_aff, "button_aff");
  GLADE_HOOKUP_OBJECT (RECHERCHE, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (RECHERCHE, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (RECHERCHE, image11, "image11");
  GLADE_HOOKUP_OBJECT (RECHERCHE, label23, "label23");

  return RECHERCHE;
}

GtkWidget*
create_MODIF (void)
{
  GtkWidget *MODIF;
  GtkWidget *fixed6;
  GtkWidget *entry_modif;
  GtkWidget *entry1;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *button_homemodif;
  GtkWidget *image13;
  GtkWidget *label34;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label24;
  GtkWidget *label35;
  GtkWidget *label30;
  GtkWidget *combobox1;
  GtkWidget *radiobutton_modifF;
  GSList *radiobutton_modifF_group = NULL;
  GtkWidget *radiobutton_modifH;
  GtkWidget *button_modif;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image14;
  GtkWidget *label25;

  MODIF = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MODIF), _("Fenetre modifier"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (MODIF), fixed6);

  entry_modif = gtk_entry_new ();
  gtk_widget_show (entry_modif);
  gtk_fixed_put (GTK_FIXED (fixed6), entry_modif, 192, 48);
  gtk_widget_set_size_request (entry_modif, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modif), 8226);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed6), entry1, 192, 96);
  gtk_widget_set_size_request (entry1, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed6), entry5, 192, 248);
  gtk_widget_set_size_request (entry5, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed6), entry6, 192, 288);
  gtk_widget_set_size_request (entry6, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  button_homemodif = gtk_button_new ();
  gtk_widget_show (button_homemodif);
  gtk_fixed_put (GTK_FIXED (fixed6), button_homemodif, 8, 8);
  gtk_widget_set_size_request (button_homemodif, 32, 32);

  image13 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_container_add (GTK_CONTAINER (button_homemodif), image13);

  label34 = gtk_label_new (_("Retour au dashboard"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed6), label34, 40, 16);
  gtk_widget_set_size_request (label34, 160, 16);

  label27 = gtk_label_new (_("Nom"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed6), label27, 128, 104);
  gtk_widget_set_size_request (label27, 49, 17);

  label28 = gtk_label_new (_("Type"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed6), label28, 128, 160);
  gtk_widget_set_size_request (label28, 49, 17);

  label29 = gtk_label_new (_("Username"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed6), label29, 112, 256);
  gtk_widget_set_size_request (label29, 72, 16);

  label24 = gtk_label_new (_("ID :"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed6), label24, 136, 48);
  gtk_widget_set_size_request (label24, 40, 32);

  label35 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed6), label35, 128, 216);
  gtk_widget_set_size_request (label35, 49, 17);

  label30 = gtk_label_new (_("Mot de passe "));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed6), label30, 88, 296);
  gtk_widget_set_size_request (label30, 104, 16);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed6), combobox1, 192, 152);
  gtk_widget_set_size_request (combobox1, 216, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Admin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Ouvrier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Technicien"));

  radiobutton_modifF = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton_modifF);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobutton_modifF, 304, 208);
  gtk_widget_set_size_request (radiobutton_modifF, 96, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_modifF), radiobutton_modifF_group);
  radiobutton_modifF_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_modifF));

  radiobutton_modifH = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton_modifH);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobutton_modifH, 192, 208);
  gtk_widget_set_size_request (radiobutton_modifH, 88, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_modifH), radiobutton_modifF_group);
  radiobutton_modifF_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_modifH));

  button_modif = gtk_button_new ();
  gtk_widget_show (button_modif);
  gtk_fixed_put (GTK_FIXED (fixed6), button_modif, 192, 328);
  gtk_widget_set_size_request (button_modif, 96, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_modif), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image14 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox9), image14, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox9), label25, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_homemodif, "clicked",
                    G_CALLBACK (on_button_homemodif_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_modifF, "toggled",
                    G_CALLBACK (on_radiobutton_modifF_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_modifH, "toggled",
                    G_CALLBACK (on_radiobutton_modifH_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_modif, "clicked",
                    G_CALLBACK (on_button_modif_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MODIF, MODIF, "MODIF");
  GLADE_HOOKUP_OBJECT (MODIF, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (MODIF, entry_modif, "entry_modif");
  GLADE_HOOKUP_OBJECT (MODIF, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (MODIF, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (MODIF, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (MODIF, button_homemodif, "button_homemodif");
  GLADE_HOOKUP_OBJECT (MODIF, image13, "image13");
  GLADE_HOOKUP_OBJECT (MODIF, label34, "label34");
  GLADE_HOOKUP_OBJECT (MODIF, label27, "label27");
  GLADE_HOOKUP_OBJECT (MODIF, label28, "label28");
  GLADE_HOOKUP_OBJECT (MODIF, label29, "label29");
  GLADE_HOOKUP_OBJECT (MODIF, label24, "label24");
  GLADE_HOOKUP_OBJECT (MODIF, label35, "label35");
  GLADE_HOOKUP_OBJECT (MODIF, label30, "label30");
  GLADE_HOOKUP_OBJECT (MODIF, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (MODIF, radiobutton_modifF, "radiobutton_modifF");
  GLADE_HOOKUP_OBJECT (MODIF, radiobutton_modifH, "radiobutton_modifH");
  GLADE_HOOKUP_OBJECT (MODIF, button_modif, "button_modif");
  GLADE_HOOKUP_OBJECT (MODIF, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (MODIF, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (MODIF, image14, "image14");
  GLADE_HOOKUP_OBJECT (MODIF, label25, "label25");

  return MODIF;
}

